jobs:
  scan:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: jdk-8
      name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      name: Get coverity cli
      run: 'wget https://scan.coverity.com/download/linux64 --no-verbose --post-data
        "token=${{ secrets.COVERITY_TOKEN }}&project=jeremylong%2FDependencyCheck"
        -O coverity_tool.tgz

        mkdir coverity_tool

        tar xzf coverity_tool.tgz --strip 1 -C coverity_tool

        '
    - continue-on-error: true
      name: Perform coverity scan
      run: 'export PATH=`pwd`/coverity_tool/bin:$PATH

        cov-build --dir cov-int mvn -DskipTests=true package --no-transfer-progress
        --batch-mode

        '
    - continue-on-error: true
      name: Submit coverity scan
      run: "tar czvf scan.tgz cov-int\ncurl --form token=${{ secrets.COVERITY_TOKEN\
        \ }} \\\n     --form email=jeremy.long@gmail.com \\\n     --form file=@scan.tgz\
        \ \\\n     --form version=\"main\" \\\n     --form description=\"Weekly Scan\"\
        \ \\\n     https://scan.coverity.com/builds?project=jeremylong%2FDependencyCheck\n"
name: coverity-scan
on:
  repository_dispatch:
    types: trigger-ga___coverity.yml
permissions:
  contents: read
