jobs:
  cleanup:
    permissions:
      actions: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
        delete_run_by_conclusion_pattern: skipped
        delete_workflow_pattern: false-positive
        keep_minimum_runs: 0
        repository: ${{ github.repository }}
        retain_days: 0
        token: ${{ github.token }}
name: False Positive Cleanup
on:
  repository_dispatch:
    types: trigger-ga___false-positive-cleanup.yml
permissions: {}
