jobs:
  maven:
    name: Regression Test Maven Plugin
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: maven-cache
      name: Check Maven Cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository/
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 6.0.x
    - continue-on-error: true
      id: jdk-8
      name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      with:
        version: 6.0.2
    - continue-on-error: true
      env:
        NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      id: build
      name: Regression Test Maven Plugin
      run: 'mvn -V -s settings.xml -pl utils,core,maven -am compile verify -DtestMavenPlugin
        -DreleaseTesting --no-transfer-progress --batch-mode

        '
    - continue-on-error: true
      id: archive-logs
      if: always()
      name: Archive IT test logs
      uses: actions/upload-artifact@v4
      with:
        name: it-test-logs
        path: maven/target/it/**/build.log
        retention-days: 7
  test:
    name: Build and Test
    permissions:
      contents: read
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: maven-cache
      name: Check Maven Cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository/
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 6.0.x
    - continue-on-error: true
      id: jdk-8
      name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 8
    - continue-on-error: true
      uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
      with:
        version: 6.0.2
    - continue-on-error: true
      id: build
      name: Test with Maven
      run: 'mvn -V -s settings.xml -pl utils,core,cli,ant,archetype -am compile verify
        --no-transfer-progress --batch-mode

        '
    - continue-on-error: true
      name: SARIF Multitool
      uses: microsoft/sarif-actions@v0.1
      with:
        command: validate core/target/test-reports/Report.sarif
name: Pull Requests
on:
  repository_dispatch:
    types: trigger-ga___pull_requests.yml
