jobs:
  build:
    name: Purge GitHub Cache
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      id: maven-cache
      name: Check Maven Cache
      uses: actions/cache@v4
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        path: ~/.m2/repository
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      id: maven-it-cache
      name: Check Local Maven Cache
      uses: actions/cache@v4
      with:
        key: mvn-it-repo
        path: maven/target/local-repo
    - continue-on-error: true
      id: odc-data-cache
      name: Check ODC Data Cache
      uses: actions/cache@v4
      with:
        key: odc-data
        path: core/target/data
    - continue-on-error: true
      name: Delete Data Directories
      run: 'rm -rf ~/.m2/repository/org/owasp/dependency-check-data

        rm -rf maven/target/local-repo/org/owasp/dependency-check-data

        rm -rf core/target/data

        '
name: Purge Cache
on:
  repository_dispatch:
    types: trigger-ga___purge-cache.yml
permissions:
  contents: read
